---
- model_name: 'drone_1'
  model_type: 'mbzirc_quadrotor'
  flight_time: 60
  position:
    xyz: [0, 0, 1.0]
    rpy: [0, 0, 0]
  payload:
    slot1:
      sensor: 'mbzirc_rf_range'
      rpy: [0, 0, 0]
    slot3:
      sensor: 'mbzirc_3d_lidar'
      rpy: [90, 0, 0]
    slot7:
      sensor: 'mbzirc_hd_camera'
      rpy: [0, 0, 0]